// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// resultC
NumericVector resultC(double hsigma, NumericVector hbeta);
RcppExport SEXP _SC19027_resultC(SEXP hsigmaSEXP, SEXP hbetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type hsigma(hsigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hbeta(hbetaSEXP);
    rcpp_result_gen = Rcpp::wrap(resultC(hsigma, hbeta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SC19027_resultC", (DL_FUNC) &_SC19027_resultC, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_SC19027(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
