# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Bias of estimated sigma and average model size using Rcpp
#' @description Bias of estimated sigma and average model size using Rcpp
#' @param hsigma the estimated sigma
#' @param hbeta the estimated coefficients
#' @return bias of estimated sigma and average model size
#' @export
resultC <- function(hsigma, hbeta) {
    .Call('_SC19027_resultC', PACKAGE = 'SC19027', hsigma, hbeta)
}

